spring.application.name=LibSmart

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.lwsnijwcitvfwgkjckvf
spring.datasource.password=afbBLg4zNpQWee

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=300000

server.port=8081

logging.level.com.example.demo=DEBUG
logging.level.org.springframework.security=DEBUG